#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <iomanip>
#include <iostream>
#include <limits>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
#include <boost/multiprecision/cpp_int.hpp>
using ull=unsigned long long; using boost::multiprecision::cpp_int; static constexpr double EPS=1e-12;
static std::vector<int> first_primes(int k){int a[]={2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71}; return std::vector<int>(a,a+k);} 
static std::vector<int> parse_csv(const std::string&s){std::vector<int>v;std::stringstream ss(s);std::string it;while(std::getline(ss,it,','))if(!it.empty())v.push_back(stoi(it));sort(v.begin(),v.end());return v;}
static std::string join_vec(const std::vector<int>&v){std::ostringstream os;os<<"[";for(size_t i=0;i<v.size();i++){if(i)os<<",";os<<v[i];}os<<"]";return os.str();}
static std::string join_primes(const std::vector<int>&v){std::ostringstream os;os<<"(";for(size_t i=0;i<v.size();i++){if(i)os<<",";os<<v[i];}os<<")";return os.str();}
static std::string idx_to_primes(const std::vector<int>&idx,const std::vector<int>&P){std::ostringstream os;os<<"[";for(size_t i=0;i<idx.size();i++){if(i)os<<",";os<<P[idx[i]];}os<<"]";return os.str();}
static unsigned long long factorial(int k){ unsigned long long r=1; for(int i=2;i<=k;i++) r*=i; return r; }
static double leading_est(const std::vector<int>& primes, ull n){ double prod=1; for(int p:primes) prod*=log((double)p); int k=primes.size(); return pow((double)n*(double)factorial(k)*prod,1.0/k); }
static cpp_int ipow(int base,int exp){cpp_int r=1,b=base; while(exp){if(exp&1)r*=b; exp>>=1; if(exp)b*=b;} return r;}
static cpp_int value_from_exps(const std::vector<int>&P,const std::vector<int>&e){cpp_int r=1; for(size_t i=0;i<P.size();i++) if(e[i]) r*=ipow(P[i],e[i]); return r;}
static int digits10(const cpp_int&x){std::stringstream ss; ss<<x; return (int)ss.str().size();}
static double approx_size(const std::vector<double>& logs,const std::vector<int>& idx,double T){int d=idx.size(); if(!d)return 1; double prod=1,f=1; for(int i:idx)prod*=logs[i]; for(int j=2;j<=d;j++)f*=j; return pow(std::max(0.0,T),d)/(f*prod)+10*pow(std::max(1.0,T),std::max(0,d-1));}
struct BuildStats{double sec=0; size_t size=0;};
static std::vector<double> gen_sums_only(const std::vector<double>&logs,const std::vector<int>&idx,double maxT,BuildStats&st){auto t0=std::chrono::high_resolution_clock::now(); int d=idx.size(); std::vector<double> sums; double est=approx_size(logs,idx,maxT); if(est>0 && est<900000000) sums.reserve((size_t)(est*1.03)); sums.push_back(0.0); if(d==0){st={0,1};return sums;} std::vector<size_t> ptr(d,0); std::vector<double>w(d); for(int j=0;j<d;j++)w[j]=logs[idx[j]]; while(true){ double best=1e300; for(int j=0;j<d;j++){ double cand=sums[ptr[j]]+w[j]; if(cand<best) best=cand; } if(best>maxT+EPS) break; sums.push_back(best); for(int j=0;j<d;j++){ while(ptr[j]<sums.size() && sums[ptr[j]]+w[j] <= best+1e-11) ptr[j]++; } }
 auto t1=std::chrono::high_resolution_clock::now(); st.sec=std::chrono::duration<double>(t1-t0).count(); st.size=sums.size(); return sums;}
static ull pair_count(const std::vector<double>&A,const std::vector<double>&B,double T){long long j=(long long)B.size()-1; ull total=0; for(size_t i=0;i<A.size();i++){double a=A[i]; while(j>=0 && a+B[j]>T+EPS)--j; if(j<0)break; total+=(ull)(j+1);} return total;}
struct Candidate{double sum; uint32_t ai,bi;};
struct SumsMITM{std::vector<int>P; std::vector<double>logs; std::vector<int>Aidx,Bidx; std::vector<double>A,B; BuildStats as,bs; double maxT; SumsMITM(std::vector<int>p,double T):P(std::move(p)),maxT(T){sort(P.begin(),P.end()); for(int q:P)logs.push_back(log((double)q)); choose_split(); A=gen_sums_only(logs,Aidx,maxT,as); B=gen_sums_only(logs,Bidx,maxT,bs); if(A.size()>B.size()){std::swap(A,B);std::swap(Aidx,Bidx);std::swap(as,bs);} }
 double approx(int mask)const{int k=P.size(),d=0;double prod=1,f=1;for(int i=0;i<k;i++)if(mask>>i&1){d++;prod*=logs[i];}for(int j=2;j<=d;j++)f*=j;return pow(maxT,d)/(f*prod);} void choose_split(){int k=P.size(),full=(1<<k)-1,best=1;double bs=1e300;for(int mask=1;mask<full;mask++){if((mask&1)==0)continue;double a=approx(mask),b=approx(full^mask),score=std::max(a,b); if(score<bs){bs=score;best=mask;}}for(int i=0;i<k;i++)((best>>i)&1?Aidx:Bidx).push_back(i);} ull count_le(double T)const{return pair_count(A,B,T);} 
 std::vector<Candidate> band(double low,double high)const{std::vector<Candidate>out; auto cmp=[](double value,double x){return value < x-EPS;}; for(uint32_t ai=0; ai<A.size(); ++ai){double a=A[ai]; if(a>high+EPS)break; auto it1=std::upper_bound(B.begin(),B.end(),low-a,cmp); auto it2=std::upper_bound(B.begin(),B.end(),high-a,cmp); uint32_t j1=(uint32_t)(it1-B.begin()), j2=(uint32_t)(it2-B.begin()); for(uint32_t bj=j1; bj<j2; ++bj){double s=a+B[bj]; if(s>low-5e-13 && s<=high+5e-13) out.push_back({s,ai,bj});}} std::sort(out.begin(),out.end(),[](const Candidate&x,const Candidate&y){if(x.sum!=y.sum)return x.sum<y.sum; if(x.ai!=y.ai)return x.ai<y.ai; return x.bi<y.bi;}); return out;}
 bool dfs_rec(const std::vector<int>&idx, int pos, double rem, std::vector<int>&loc, double tol) const { if(pos==(int)idx.size()){ return fabs(rem)<=tol; } double w=logs[idx[pos]]; int maxe=(int)floor((rem+tol)/w); if(maxe<0) return false; // heuristic around largest expected exponent first? iterate 0..max
   for(int e=0;e<=maxe;e++){ loc[pos]=e; double nr=rem-e*w; if(nr<-tol) break; if(dfs_rec(idx,pos+1,nr,loc,tol)) return true; } loc[pos]=0; return false; }
 std::vector<int> reconstruct(double sumA,double sumB) const {std::vector<int>e(P.size(),0); std::vector<int>la(Aidx.size(),0), lb(Bidx.size(),0); bool oka=dfs_rec(Aidx,0,sumA,la,5e-10), okb=dfs_rec(Bidx,0,sumB,lb,5e-10); if(!oka||!okb){ // loosen tolerance
    oka=dfs_rec(Aidx,0,sumA,la,5e-8); okb=dfs_rec(Bidx,0,sumB,lb,5e-8);
 }
 if(!oka||!okb) throw std::runtime_error("reconstruct failed"); for(size_t i=0;i<Aidx.size();i++)e[Aidx[i]]=la[i]; for(size_t i=0;i<Bidx.size();i++)e[Bidx[i]]=lb[i]; return e;}
};
struct Result{double sec,build,count,band;std::vector<int>exps;int digits;size_t A,B,bandn;int calls;ull gap;std::vector<int>Aidx,Bidx;};
static Result nth_sums(std::vector<int>P,ull n,ull target_gap=20000){auto t0=std::chrono::high_resolution_clock::now(); double est=leading_est(P,n),maxT=std::max(1e-9,est*1.02+1e-8); auto tb0=std::chrono::high_resolution_clock::now(); std::unique_ptr<SumsMITM>R(new SumsMITM(P,maxT)); auto tb1=std::chrono::high_resolution_clock::now(); int calls=0; auto count=[&](double T){calls++;return R->count_le(T);}; double lo=std::max(0.0,est*.70),hi=maxT; ull c_hi=count(hi); while(c_hi<n){maxT*=1.25; tb0=std::chrono::high_resolution_clock::now();R.reset(new SumsMITM(P,maxT));tb1=std::chrono::high_resolution_clock::now();hi=maxT;c_hi=count(hi);} ull c_lo=count(lo); while(c_lo>=n){hi=lo;c_hi=c_lo;lo*=.75;c_lo=count(lo);} auto tc0=std::chrono::high_resolution_clock::now(); int stagnant=0; for(int iter=0;iter<48;iter++){ull gap=c_hi-c_lo; if(gap<=target_gap)break; long double frac=((long double)n-c_lo)/((long double)c_hi-c_lo); if(!(frac>0&&frac<1))frac=.5; frac=std::min((long double).985,std::max((long double).015,frac)); double t=lo+(double)frac*(hi-lo); if(t<=lo+1e-14*(1+fabs(lo))||t>=hi-1e-14*(1+fabs(hi))||stagnant>=4){t=(lo+hi)/2;stagnant=0;} ull c=count(t); ull oldgap=gap; if(c>=n){hi=t;c_hi=c;}else{lo=t;c_lo=c;} ull ng=c_hi-c_lo; if(ng>oldgap*95/100)stagnant++;else stagnant=0;} for(int iter=0;iter<50&&c_hi-c_lo>target_gap;iter++){double mid=(lo+hi)/2; ull c=count(mid); if(c>=n){hi=mid;c_hi=c;}else{lo=mid;c_lo=c;}} auto tc1=std::chrono::high_resolution_clock::now(); auto tb2=std::chrono::high_resolution_clock::now(); std::vector<Candidate>cands; ull below=0; long long off=-1; double L=lo,H=hi; for(int attempt=0;attempt<10;attempt++){below=count(L); cands=R->band(L,H); off=(long long)n-(long long)below-1; if(off>=0&&(size_t)off<cands.size())break; double w=H-L;if(w<=0)w=1e-10*(1+fabs(H));L=std::max(-1e-9,L-w);H+=w;} if(!(off>=0&&(size_t)off<cands.size()))throw std::runtime_error("band fail"); auto chosen=cands[(size_t)off]; auto exps=R->reconstruct(R->A[chosen.ai],R->B[chosen.bi]); auto tb3=std::chrono::high_resolution_clock::now(); auto val=value_from_exps(P,exps); auto t1=std::chrono::high_resolution_clock::now(); return {std::chrono::duration<double>(t1-t0).count(), std::chrono::duration<double>(tb1-tb0).count(), std::chrono::duration<double>(tc1-tc0).count(), std::chrono::duration<double>(tb3-tb2).count(), exps, digits10(val), R->A.size(), R->B.size(), cands.size(), calls, c_hi-c_lo, R->Aidx, R->Bidx};}
int main(int argc,char**argv){std::cout.setf(std::ios::fixed); std::cout<<std::setprecision(6); try{ if(argc>=2&&std::string(argv[1])=="nth"){auto P=parse_csv(argv[2]); ull n=std::stoull(argv[3]); auto r=nth_sums(P,n); std::cout<<"sums_only_mitm P="<<join_primes(P)<<" k="<<P.size()<<" N="<<n<<" seconds="<<r.sec<<" build="<<r.build<<" count="<<r.count<<" band_phase="<<r.band<<" A="<<r.A<<" B="<<r.B<<" band="<<r.bandn<<" calls="<<r.calls<<" gap="<<r.gap<<" exps="<<join_vec(r.exps)<<" digits="<<r.digits<<" splitA="<<idx_to_primes(r.Aidx,P)<<" splitB="<<idx_to_primes(r.Bidx,P)<<"\n"; return 0;} for(int k:{6,8,10,12}){auto r=nth_sums(first_primes(k),1000000000000ULL); std::cout<<"sums_only_mitm P="<<join_primes(first_primes(k))<<" k="<<k<<" N=1000000000000 seconds="<<r.sec<<" build="<<r.build<<" count="<<r.count<<" band_phase="<<r.band<<" A="<<r.A<<" B="<<r.B<<" band="<<r.bandn<<" calls="<<r.calls<<" gap="<<r.gap<<" exps="<<join_vec(r.exps)<<" digits="<<r.digits<<" splitA="<<idx_to_primes(r.Aidx,first_primes(k))<<" splitB="<<idx_to_primes(r.Bidx,first_primes(k))<<"\n"; }}catch(std::exception&e){std::cerr<<"error: "<<e.what()<<"\n"; return 1;}}
