#include <algorithm>
#include <chrono>
#include <cstdint>
#include <exception>
#include <iostream>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>

#include <boost/multiprecision/cpp_int.hpp>

using ull = unsigned long long;
using i128 = __int128_t;
using u128 = __uint128_t;
using boost::multiprecision::cpp_int;

struct LB64 { long long lo; long long hi; };
struct ExpPack { uint64_t lo=0; uint64_t hi=0; };
struct Entry { long long lo; uint32_t width; ExpPack pack; inline long long hi() const { return lo + (long long)width; } };

static std::string i128_to_string(i128 x) {
    if (x == 0) return "0";
    bool neg = x < 0;
    u128 y = neg ? (u128)(-x) : (u128)x;
    std::string s;
    while (y) { s.push_back('0' + (int)(y % 10)); y /= 10; }
    if (neg) s.push_back('-');
    std::reverse(s.begin(), s.end());
    return s;
}
static std::string u128_to_string(u128 x) {
    if (x == 0) return "0";
    std::string s;
    while (x) { s.push_back('0' + (int)(x % 10)); x /= 10; }
    std::reverse(s.begin(), s.end());
    return s;
}

static std::vector<int> parse_csv_ints(const std::string& s) {
    std::vector<int> out;
    std::stringstream ss(s); std::string item;
    while (std::getline(ss, item, ',')) if (!item.empty()) out.push_back(std::stoi(item));
    if (out.empty()) throw std::runtime_error("empty csv");
    return out;
}
static std::string vec_to_string(const std::vector<int>& v) {
    std::ostringstream oss; oss << "[";
    for (size_t i=0;i<v.size();++i){ if(i)oss<<","; oss<<v[i]; }
    oss << "]"; return oss.str();
}
static LB64 get_log_bound_1e15(int p) {
    // Rigorous integer bounds for 1e15 * ln(p), generated by exact rational
    // 2*atanh series with rational tail bounds after powers-of-two range
    // reduction. Constants include a small integer safety margin.
    switch (p) {
        case 2:  return {  693147180559941LL,   693147180559950LL};
        case 3:  return { 1098612288668105LL,  1098612288668116LL};
        case 5:  return { 1609437912434095LL,  1609437912434106LL};
        case 7:  return { 1945910149055308LL,  1945910149055320LL};
        case 11: return { 2397895272798365LL,  2397895272798377LL};
        case 13: return { 2564949357461531LL,  2564949357461544LL};
        case 17: return { 2833213344056210LL,  2833213344056223LL};
        case 19: return { 2944438979166435LL,  2944438979166448LL};
        case 23: return { 3135494215929144LL,  3135494215929157LL};
        case 29: return { 3367295829986469LL,  3367295829986483LL};
        case 31: return { 3433987204485140LL,  3433987204485154LL};
        case 37: return { 3610917912644218LL,  3610917912644232LL};
        default: throw std::runtime_error("this auditor currently supports primes {2,3,5,7,11,13,17,19,23,29,31,37}");
    }
}
static inline ExpPack pack_set(ExpPack pack, int pos, int exp) {
    if (exp < 0 || exp > 65535) throw std::runtime_error("exponent too large for 16-bit pack");
    if (pos < 4) {
        pack.lo |= (uint64_t(exp) << (16 * pos));
    } else if (pos < 8) {
        pack.hi |= (uint64_t(exp) << (16 * (pos - 4)));
    } else {
        throw std::runtime_error("auditor exponent pack supports at most 8 coordinates per side");
    }
    return pack;
}
static inline int pack_get(ExpPack pack, int pos) {
    if (pos < 4) return int((pack.lo >> (16*pos)) & 0xFFFFULL);
    if (pos < 8) return int((pack.hi >> (16*(pos-4))) & 0xFFFFULL);
    throw std::runtime_error("auditor exponent pack supports at most 8 coordinates per side");
}

struct PowerCache {
    std::vector<int> primes;
    std::vector<std::vector<cpp_int>> powers;
    explicit PowerCache(std::vector<int> p) : primes(std::move(p)), powers(primes.size()) {
        for (auto& v : powers) v.push_back(cpp_int(1));
    }
    void ensure(size_t i, int exp) {
        auto& v = powers[i];
        while ((int)v.size() <= exp) v.push_back(v.back() * primes[i]);
    }
    void ensure_all(const std::vector<int>& exps) { for(size_t i=0;i<exps.size();++i) ensure(i, exps[i]); }
    cpp_int product(const std::vector<int>& exps) {
        ensure_all(exps);
        cpp_int r=1; for(size_t i=0;i<exps.size();++i) r *= powers[i][exps[i]]; return r;
    }
};

struct K3AuditResult {
    ull count=0;
    ull outer_terms=0;
    ull ambiguous_possible=0;
    ull ambiguous_resolved=0;
};

static ull floor_div_nonneg(i128 num, i128 den) {
    if (num < 0) return 0;
    return (ull)(num / den);
}

static ull count2_scaled(long long w0, long long w1, i128 threshold) {
    if (threshold < 0) return 0;
    i128 loop_w = w0, solve_w = w1;
    if (loop_w < solve_w) std::swap(loop_w, solve_w);
    ull m = floor_div_nonneg(threshold, loop_w);
    ull total = 0;
    for (ull e=0; e<=m; ++e) {
        total += floor_div_nonneg(threshold - (i128)e * loop_w, solve_w) + 1ULL;
    }
    return total;
}

static bool exact_leq_k3(PowerCache& cache, const std::vector<int>& exps, const cpp_int& target) {
    return cache.product(exps) <= target;
}

static K3AuditResult count_le_k3_interval(const std::vector<int>& primes, const std::vector<int>& exps) {
    if (primes.size() != 3 || exps.size() != 3) throw std::runtime_error("k3 audit requires exactly three coordinates");
    std::vector<LB64> lbs;
    for (int q: primes) lbs.push_back(get_log_bound_1e15(q));
    i128 Tlo=0, Thi=0;
    for (size_t i=0; i<3; ++i) {
        Tlo += (i128)exps[i] * lbs[i].lo;
        Thi += (i128)exps[i] * lbs[i].hi;
    }
    PowerCache cache(primes);
    cpp_int target = cache.product(exps);

    int outer = 0;
    for (int i=1; i<3; ++i) if (lbs[i].lo > lbs[outer].lo) outer = i;
    std::vector<int> inner;
    for (int i=0; i<3; ++i) if (i != outer) inner.push_back(i);
    int i0 = inner[0], i1 = inner[1];

    ull max_outer = floor_div_nonneg(Thi, lbs[outer].lo);
    K3AuditResult result;
    result.outer_terms = max_outer + 1ULL;
    for (ull eo=0; eo<=max_outer; ++eo) {
        i128 definite_thr = Tlo - (i128)eo * lbs[outer].hi;
        i128 possible_thr = Thi - (i128)eo * lbs[outer].lo;
        ull definite = count2_scaled(lbs[i0].hi, lbs[i1].hi, definite_thr);
        ull possible = count2_scaled(lbs[i0].lo, lbs[i1].lo, possible_thr);
        if (possible < definite) possible = definite;
        result.count += definite;
        if (possible == definite) continue;
        result.ambiguous_possible += possible - definite;
        if (result.ambiguous_possible > 2000000ULL) throw std::runtime_error("too many ambiguous k3 comparisons");
        ull max_e0 = floor_div_nonneg(possible_thr, lbs[i0].lo);
        for (ull e0=0; e0<=max_e0; ++e0) {
            i128 poss_rem = possible_thr - (i128)e0 * lbs[i0].lo;
            ull e1_poss = floor_div_nonneg(poss_rem, lbs[i1].lo);
            i128 def_rem = definite_thr - (i128)e0 * lbs[i0].hi;
            long long e1_def = def_rem < 0 ? -1 : (long long)floor_div_nonneg(def_rem, lbs[i1].hi);
            ull start = e1_def < 0 ? 0ULL : (ull)e1_def + 1ULL;
            if (start > e1_poss) continue;
            for (ull e1=start; e1<=e1_poss; ++e1) {
                std::vector<int> candidate(3,0);
                candidate[outer] = (int)eo;
                candidate[i0] = (int)e0;
                candidate[i1] = (int)e1;
                if (exact_leq_k3(cache, candidate, target)) ++result.count;
                ++result.ambiguous_resolved;
            }
        }
    }
    return result;
}

struct Auditor {
    std::vector<int> primes, exps;
    std::vector<LB64> lbs;
    long long Tlo=0, Thi=0;
    cpp_int target;
    PowerCache cache;
    ull ambiguous_possible=0, ambiguous_resolved=0;
    size_t groupA=0, groupB=0, overlapsB=0;
    std::vector<int> chosenAidx, chosenBidx;

    Auditor(std::vector<int> p, std::vector<int> e) : primes(std::move(p)), exps(std::move(e)), cache(primes) {
        if (primes.size() != exps.size()) throw std::runtime_error("prime/exponent length mismatch");
        if (primes.empty() || primes.size() > 12) throw std::runtime_error("this auditor supports 1..12 primes");
        for (int q: primes) lbs.push_back(get_log_bound_1e15(q));
        for (size_t i=0;i<primes.size();++i) {
            __int128 a = (__int128)exps[i] * lbs[i].lo;
            __int128 b = (__int128)exps[i] * lbs[i].hi;
            __int128 nlo = (__int128)Tlo + a;
            __int128 nhi = (__int128)Thi + b;
            if (nlo > std::numeric_limits<long long>::max() || nhi > std::numeric_limits<long long>::max()) throw std::runtime_error("scaled interval overflow");
            Tlo = (long long)nlo; Thi = (long long)nhi;
        }
        std::vector<int> maxe = exps;
        for (int& z: maxe) z += 4;
        cache.ensure_all(maxe);
        target = cache.product(exps);
    }
    bool exact_leq(const std::vector<int>& e) { return cache.product(e) <= target; }
    std::vector<int> full_exps(const std::vector<int>& Aidx, const Entry& a, const std::vector<int>& Bidx, const Entry& b) {
        std::vector<int> e(primes.size(), 0);
        for(int i=0;i<(int)Aidx.size();++i) e[Aidx[i]] = pack_get(a.pack, i);
        for(int i=0;i<(int)Bidx.size();++i) e[Bidx[i]] = pack_get(b.pack, i);
        return e;
    }
    void gen_rec(const std::vector<int>& idxs, int pos, long long lo, uint32_t width, ExpPack pack, std::vector<Entry>& out) {
        if (pos == (int)idxs.size()) { out.push_back({lo,width,pack}); return; }
        int idx = idxs[pos];
        const long long L = lbs[idx].lo;
        const uint32_t W = (uint32_t)(lbs[idx].hi - lbs[idx].lo);
        for (int e=0;;++e) {
            __int128 nlo128 = (__int128)lo + (__int128)e * L;
            if (nlo128 > Thi) break;
            uint32_t nw = width + (uint32_t)e * W;
            gen_rec(idxs, pos+1, (long long)nlo128, nw, pack_set(pack,pos,e), out);
        }
    }
    std::vector<Entry> gen_group(const std::vector<int>& idxs, bool sortit) {
        std::vector<Entry> out;
        gen_rec(idxs, 0, 0LL, 0U, ExpPack{}, out);
        if (sortit) std::sort(out.begin(), out.end(), [](const Entry& a, const Entry& b){
            if (a.lo != b.lo) return a.lo < b.lo;
            if (a.width != b.width) return a.width < b.width;
            if (a.pack.lo != b.pack.lo) return a.pack.lo < b.pack.lo;
            return a.pack.hi < b.pack.hi;
        });
        return out;
    }
    long double approx_group_size_mask(int mask) const {
        int d=0;
        long double prod=1.0L;
        long double T=(long double)(Tlo + (Thi-Tlo)/2) / 1.0e15L;
        for (int i=0; i<(int)primes.size(); ++i) {
            if (mask>>i & 1) {
                ++d;
                prod *= ((long double)lbs[i].lo / 1.0e15L);
            }
        }
        if (d==0) return 1.0L;
        long double f=1.0L;
        for (int i=2; i<=d; ++i) f *= (long double)i;
        long double main = std::pow(std::max(0.0L,T), d)/(f*prod);
        long double boundary = 10.0L*std::pow(std::max(1.0L,T), std::max(0,d-1));
        return main + boundary;
    }
    void choose_split(std::vector<int>& Aidx, std::vector<int>& Bidx) const {
        int k=(int)primes.size();
        int full=(1<<k)-1;
        int best=1;
        long double best_score=std::numeric_limits<long double>::infinity();
        for (int mask=1; mask<full; ++mask) {
            int ad=__builtin_popcount((unsigned)mask);
            int bd=k-ad;
            if (ad>8 || bd>8) continue;
            int canon = std::min(mask, full^mask);
            if (mask != canon) continue;
            long double a=approx_group_size_mask(mask);
            long double b=approx_group_size_mask(full^mask);
            long double score=std::max(a,b) + 0.05L*(a+b);
            if (score < best_score) { best_score=score; best=mask; }
        }
        int comp=full^best;
        long double a=approx_group_size_mask(best);
        long double b=approx_group_size_mask(comp);
        if (a <= b) {
            for (int i=0;i<k;++i) ((best>>i)&1 ? Aidx : Bidx).push_back(i);
        } else {
            for (int i=0;i<k;++i) ((comp>>i)&1 ? Aidx : Bidx).push_back(i);
        }
    }
    ull count_le() {
        std::vector<int> Aidx, Bidx;
        choose_split(Aidx, Bidx);
        if (Aidx.size() > 8 || Bidx.size() > 8) throw std::runtime_error("auditor split pack supports at most 8 coordinates per side");
        chosenAidx = Aidx;
        chosenBidx = Bidx;
        std::vector<Entry> A = gen_group(Aidx, false);
        std::vector<Entry> B = gen_group(Bidx, true);
        groupA = A.size(); groupB = B.size();
        if (!B.empty()) {
            long long prev_hi = B[0].hi();
            for(size_t i=1;i<B.size();++i){ if(prev_hi >= B[i].lo) ++overlapsB; if(B[i].hi() > prev_hi) prev_hi = B[i].hi(); }
        }
        if (overlapsB != 0) throw std::runtime_error("interval overlaps in sorted B; robust overlap fallback not implemented");
        auto upper_hi = [&](long long threshold)->size_t{
            size_t lo=0, hi=B.size();
            while(lo<hi){ size_t m=lo+(hi-lo)/2; if(B[m].hi() <= threshold) lo=m+1; else hi=m; }
            return lo;
        };
        auto upper_lo = [&](long long threshold)->size_t{
            size_t lo=0, hi=B.size();
            while(lo<hi){ size_t m=lo+(hi-lo)/2; if(B[m].lo <= threshold) lo=m+1; else hi=m; }
            return lo;
        };
        ull total=0;
        for (const auto& a: A) {
            long long definite_thr = Tlo - a.hi();
            long long possible_thr = Thi - a.lo;
            size_t def = upper_hi(definite_thr);
            size_t poss = upper_lo(possible_thr);
            if (poss < def) poss = def;
            total += (ull)def;
            if (poss > def) {
                ambiguous_possible += (ull)(poss - def);
                if (ambiguous_possible > 2000000ULL) throw std::runtime_error("too many ambiguous comparisons");
                for(size_t j=def;j<poss;++j){
                    auto e = full_exps(Aidx, a, Bidx, B[j]);
                    if (exact_leq(e)) ++total;
                    ++ambiguous_resolved;
                }
            }
        }
        return total;
    }
};

int main(int argc, char** argv) {
    try {
        if (argc < 4) {
            std::cerr << "usage: " << argv[0] << " primes_csv exps_csv expected_N\n";
            return 2;
        }
        auto primes = parse_csv_ints(argv[1]);
        auto exps = parse_csv_ints(argv[2]);
        ull expected = std::stoull(argv[3]);
        auto start = std::chrono::high_resolution_clock::now();
        if (primes.size() == 3) {
            auto cert = count_le_k3_interval(primes, exps);
            auto end = std::chrono::high_resolution_clock::now();
            double sec = std::chrono::duration<double>(end-start).count();
            bool ok = (cert.count == expected);
            std::cout << "interval_audit_exps P=" << vec_to_string(primes)
                      << " exps=" << vec_to_string(exps)
                      << " expected_N=" << expected
                      << " certified_count_le=" << cert.count
                      << " rank_certified=" << (ok?"true":"false")
                      << " method=k3_interval_floor_sum"
                      << " groupA=" << cert.outer_terms
                      << " groupB=0"
                      << " overlapsB=0"
                      << " ambiguous_possible=" << cert.ambiguous_possible
                      << " ambiguous_resolved=" << cert.ambiguous_resolved
                      << " cert_seconds=" << sec
                      << "\n";
            return ok ? 0 : 1;
        }
        Auditor aud(primes, exps);
        ull cnt = aud.count_le();
        auto end = std::chrono::high_resolution_clock::now();
        double sec = std::chrono::duration<double>(end-start).count();
        bool ok = (cnt == expected);
        std::cout << "interval_audit_exps P=" << vec_to_string(primes)
                  << " exps=" << vec_to_string(exps)
                  << " expected_N=" << expected
                  << " certified_count_le=" << cnt
                  << " rank_certified=" << (ok?"true":"false")
                  << " groupA=" << aud.groupA
                  << " groupB=" << aud.groupB
                  << " overlapsB=" << aud.overlapsB
                  << " ambiguous_possible=" << aud.ambiguous_possible
                  << " ambiguous_resolved=" << aud.ambiguous_resolved
                  << " cert_seconds=" << sec
                  << "\n";
        return ok ? 0 : 1;
    } catch (const std::exception& e) {
        std::cerr << "ERROR: " << e.what() << "\n";
        return 1;
    }
}
