#include <algorithm>
#include <chrono>
#include <cstdint>
#include <exception>
#include <iostream>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>

#include <boost/multiprecision/cpp_int.hpp>

using ull = unsigned long long;
using i128 = __int128_t;
using u128 = __uint128_t;
using boost::multiprecision::cpp_int;

struct LB64 { long long lo; long long hi; };
struct Entry { long long lo; uint32_t width; uint64_t pack; inline long long hi() const { return lo + (long long)width; } };

static std::string i128_to_string(i128 x) {
    if (x == 0) return "0";
    bool neg = x < 0;
    u128 y = neg ? (u128)(-x) : (u128)x;
    std::string s;
    while (y) { s.push_back('0' + (int)(y % 10)); y /= 10; }
    if (neg) s.push_back('-');
    std::reverse(s.begin(), s.end());
    return s;
}

static std::vector<int> parse_csv_ints(const std::string& s) {
    std::vector<int> out;
    std::stringstream ss(s); std::string item;
    while (std::getline(ss, item, ',')) if (!item.empty()) out.push_back(std::stoi(item));
    if (out.empty()) throw std::runtime_error("empty csv");
    return out;
}
static std::string vec_to_string(const std::vector<int>& v) {
    std::ostringstream oss; oss << "[";
    for (size_t i=0;i<v.size();++i){ if(i)oss<<","; oss<<v[i]; }
    oss << "]"; return oss.str();
}
static LB64 get_log_bound_1e15(int p) {
    // Rigorous integer bounds for 1e15 * ln(p), generated by exact rational
    // 2*atanh series with rational tail bounds. Widths are deliberately wider
    // than nearest-integer constants so this file remains self-contained.
    switch (p) {
        case 2:  return {  693147180559937LL,   693147180559954LL};
        case 3:  return { 1098612288668088LL,  1098612288668132LL};
        case 5:  return { 1609437912434080LL,  1609437912434123LL};
        case 7:  return { 1945910149055284LL,  1945910149055342LL};
        case 11: return { 2397895272798331LL,  2397895272798410LL};
        case 13: return { 2564949357461499LL,  2564949357461576LL};
        default: throw std::runtime_error("this auditor currently supports primes {2,3,5,7,11,13}");
    }
}
static inline uint64_t pack_set(uint64_t pack, int pos, int exp) {
    if (exp < 0 || exp > 65535) throw std::runtime_error("exponent too large for 16-bit pack");
    return pack | (uint64_t(exp) << (16 * pos));
}
static inline int pack_get(uint64_t pack, int pos) { return int((pack >> (16*pos)) & 0xFFFFULL); }

struct PowerCache {
    std::vector<int> primes;
    std::vector<std::vector<cpp_int>> powers;
    explicit PowerCache(std::vector<int> p) : primes(std::move(p)), powers(primes.size()) {
        for (auto& v : powers) v.push_back(cpp_int(1));
    }
    void ensure(size_t i, int exp) {
        auto& v = powers[i];
        while ((int)v.size() <= exp) v.push_back(v.back() * primes[i]);
    }
    void ensure_all(const std::vector<int>& exps) { for(size_t i=0;i<exps.size();++i) ensure(i, exps[i]); }
    cpp_int product(const std::vector<int>& exps) {
        ensure_all(exps);
        cpp_int r=1; for(size_t i=0;i<exps.size();++i) r *= powers[i][exps[i]]; return r;
    }
};

struct Auditor {
    std::vector<int> primes, exps;
    std::vector<LB64> lbs;
    long long Tlo=0, Thi=0;
    cpp_int target;
    PowerCache cache;
    ull ambiguous_possible=0, ambiguous_resolved=0;
    size_t groupA=0, groupB=0, overlapsB=0;

    Auditor(std::vector<int> p, std::vector<int> e) : primes(std::move(p)), exps(std::move(e)), cache(primes) {
        if (primes.size() != exps.size()) throw std::runtime_error("prime/exponent length mismatch");
        if (primes.empty() || primes.size() > 6) throw std::runtime_error("this auditor supports 1..6 primes");
        for (int q: primes) lbs.push_back(get_log_bound_1e15(q));
        for (size_t i=0;i<primes.size();++i) {
            __int128 a = (__int128)exps[i] * lbs[i].lo;
            __int128 b = (__int128)exps[i] * lbs[i].hi;
            __int128 nlo = (__int128)Tlo + a;
            __int128 nhi = (__int128)Thi + b;
            if (nlo > std::numeric_limits<long long>::max() || nhi > std::numeric_limits<long long>::max()) throw std::runtime_error("scaled interval overflow");
            Tlo = (long long)nlo; Thi = (long long)nhi;
        }
        std::vector<int> maxe = exps;
        for (int& z: maxe) z += 4;
        cache.ensure_all(maxe);
        target = cache.product(exps);
    }
    bool exact_leq(const std::vector<int>& e) { return cache.product(e) <= target; }
    std::vector<int> full_exps(const std::vector<int>& Aidx, const Entry& a, const std::vector<int>& Bidx, const Entry& b) {
        std::vector<int> e(primes.size(), 0);
        for(int i=0;i<(int)Aidx.size();++i) e[Aidx[i]] = pack_get(a.pack, i);
        for(int i=0;i<(int)Bidx.size();++i) e[Bidx[i]] = pack_get(b.pack, i);
        return e;
    }
    void gen_rec(const std::vector<int>& idxs, int pos, long long lo, uint32_t width, uint64_t pack, std::vector<Entry>& out) {
        if (pos == (int)idxs.size()) { out.push_back({lo,width,pack}); return; }
        int idx = idxs[pos];
        const long long L = lbs[idx].lo;
        const uint32_t W = (uint32_t)(lbs[idx].hi - lbs[idx].lo);
        for (int e=0;;++e) {
            __int128 nlo128 = (__int128)lo + (__int128)e * L;
            if (nlo128 > Thi) break;
            uint32_t nw = width + (uint32_t)e * W;
            gen_rec(idxs, pos+1, (long long)nlo128, nw, pack_set(pack,pos,e), out);
        }
    }
    std::vector<Entry> gen_group(const std::vector<int>& idxs, bool sortit) {
        std::vector<Entry> out;
        gen_rec(idxs, 0, 0LL, 0U, 0ULL, out);
        if (sortit) std::sort(out.begin(), out.end(), [](const Entry& a, const Entry& b){
            if (a.lo != b.lo) return a.lo < b.lo;
            if (a.width != b.width) return a.width < b.width;
            return a.pack < b.pack;
        });
        return out;
    }
    ull count_le() {
        const int k = (int)primes.size();
        std::vector<int> Aidx, Bidx;
        if (k==1) { Aidx={}; Bidx={0}; }
        else if (k==2) { Aidx={0}; Bidx={1}; }
        else if (k==3) { Aidx={0}; Bidx={1,2}; }
        else if (k==4) { Aidx={0,1}; Bidx={2,3}; }
        else if (k==5) { Aidx={0,1}; Bidx={2,3,4}; }
        else if (k==6) { Aidx={0,1,2}; Bidx={3,4,5}; }
        std::vector<Entry> A = gen_group(Aidx, false);
        std::vector<Entry> B = gen_group(Bidx, true);
        groupA = A.size(); groupB = B.size();
        if (!B.empty()) {
            long long prev_hi = B[0].hi();
            for(size_t i=1;i<B.size();++i){ if(prev_hi >= B[i].lo) ++overlapsB; if(B[i].hi() > prev_hi) prev_hi = B[i].hi(); }
        }
        if (overlapsB != 0) throw std::runtime_error("interval overlaps in sorted B; robust overlap fallback not implemented");
        auto upper_hi = [&](long long threshold)->size_t{
            size_t lo=0, hi=B.size();
            while(lo<hi){ size_t m=lo+(hi-lo)/2; if(B[m].hi() <= threshold) lo=m+1; else hi=m; }
            return lo;
        };
        auto upper_lo = [&](long long threshold)->size_t{
            size_t lo=0, hi=B.size();
            while(lo<hi){ size_t m=lo+(hi-lo)/2; if(B[m].lo <= threshold) lo=m+1; else hi=m; }
            return lo;
        };
        ull total=0;
        for (const auto& a: A) {
            long long definite_thr = Tlo - a.hi();
            long long possible_thr = Thi - a.lo;
            size_t def = upper_hi(definite_thr);
            size_t poss = upper_lo(possible_thr);
            if (poss < def) poss = def;
            total += (ull)def;
            if (poss > def) {
                ambiguous_possible += (ull)(poss - def);
                if (ambiguous_possible > 2000000ULL) throw std::runtime_error("too many ambiguous comparisons");
                for(size_t j=def;j<poss;++j){
                    auto e = full_exps(Aidx, a, Bidx, B[j]);
                    if (exact_leq(e)) ++total;
                    ++ambiguous_resolved;
                }
            }
        }
        return total;
    }
};

int main(int argc, char** argv) {
    try {
        if (argc < 4) {
            std::cerr << "usage: " << argv[0] << " primes_csv exps_csv expected_N\n";
            return 2;
        }
        auto primes = parse_csv_ints(argv[1]);
        auto exps = parse_csv_ints(argv[2]);
        ull expected = std::stoull(argv[3]);
        auto start = std::chrono::high_resolution_clock::now();
        Auditor aud(primes, exps);
        ull cnt = aud.count_le();
        auto end = std::chrono::high_resolution_clock::now();
        double sec = std::chrono::duration<double>(end-start).count();
        bool ok = (cnt == expected);
        std::cout << "interval_audit_exps P=" << vec_to_string(primes)
                  << " exps=" << vec_to_string(exps)
                  << " expected_N=" << expected
                  << " certified_count_le=" << cnt
                  << " rank_certified=" << (ok?"true":"false")
                  << " groupA=" << aud.groupA
                  << " groupB=" << aud.groupB
                  << " overlapsB=" << aud.overlapsB
                  << " ambiguous_possible=" << aud.ambiguous_possible
                  << " ambiguous_resolved=" << aud.ambiguous_resolved
                  << " cert_seconds=" << sec
                  << "\n";
        return ok ? 0 : 1;
    } catch (const std::exception& e) {
        std::cerr << "ERROR: " << e.what() << "\n";
        return 1;
    }
}
